site_name: Docs - Infinite Developer
site_url: https://docs.cubixdev.org
site_description: Cubix Infinite Developer Documentation
site_author: Cubix Entertainment

repo_url: https://github.com/mkdocs/mkdocs-bootswatch

copyright: Copyright &copy; Cubix Entertainment LLC 2025 | All rights reserved. <br>Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>.

theme:
    name: slate

markdown_extensions:
    - toc:
        permalink: '#'

plugins:
    - search
