site_name: Infinite Developer Docs
site_url: https://docs.cubixdev.org
site_description: Cubix Infinite Developer Documentation
site_author: Cubix Entertainment

copyright: Copyright &copy; 2025 Cubix Entertainment LLC | All rights reserved. <br>Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>.

theme:
    custom_dir: mkdocs_bootswatch/infinite
    name: mkdocs
    highlightjs: true
    hljs_style: tokyo-night-dark

markdown_extensions:
    - footnotes
    - pymdownx.superfences
    - pymdownx.tasklist
    - pymdownx.mark
    - toc:
        permalink: "*"

plugins:
    - search
